# Introduction to Data Science and Programming, Autumn 2025

## Coding test, September 30, 2025

There are three tasks, each giving 2 points. The coding test is approved if you get at least 3 out of 6 points. In case it is not approved, you can take a re-test at the end of October. Your code is to submitted as Jupyter notebook on learnIT. During the coding test timeslot, you can submit as many times as you want, your last submission counts.

If you take this test, you confirm the following:

> I agree that copy-pasting code from others (including the internet) or communicating with others during the test is not allowed and counts as cheating. My solutions to this test reflect my own work only. I understand that apart from the above, I can use any aids during this test, including my own
notes/code, lecture material, or looking up syntax on the internet, for example how to write a list comprehension, or names/parameters/uses of functions. 

Suspicious submissions will be checked carefully and, in case, initiate a case for [exam fraud](https://itustudent.itu.dk/Study-Administration/Exams/Academic-Misconduct#:~:text=If%20you%20are%20being%20suspected,Expulsion%20from). 

You may import any modules you want to work with, even if they were not covered in the lecture.

***

Before you turn this assignment in, make sure everything runs as expected. (Go to `Restart and run all` - should not throw any assertion errors.) 

Make sure you fill in any place that says `YOUR CODE HERE`, as well as your name and ITU email address below:

In [ ]:
NAME = "Krzysztof Marcinkiewicz"
ITU_MAIL = "krzm@itu.dk" # xxxx@itu.dk

***

# Task & skills overview

## Task 1: Password checker

Skills:
* writing functions
* string methods
* using lists and sets
* conditional statements 
* Boolean logic

## Task 2: Dice games

Skills:
* writing functions
* while loops
* conditional statements 
* the `random` module
* debugging code

## Task 3: `countries.csv` with `pandas`

Skills:
* reading in tabular data with the `pandas` package
* filtering of pandas DataFrames with Boolean indexing
* creating copies of DataFrame subsets using `.copy()`
* sorting values in a DataFrame

***
***

# Task 1: Password checker

The IT department at ITU noticed that many students and employees at ITU use passwords that are too easy to guess. Therefore, the IT department made up the following rules for new passwords.

1. A password has to have at least 12 characters.
2. A password cannot consist of only identical characters (e.g., "aaaaa" or "bbbbbbbbb" are not allowed).
3. A password has to contain at least one lowercase letter **and** at least one uppercase letter. (Hint: the string methods [`islower()`](https://docs.python.org/3/library/stdtypes.html#str.islower) and [`isupper()`](https://docs.python.org/3/library/stdtypes.html#str.isupper) might be useful here)

Now, the IT department needs your help! They asked you to implement a validity checker that will check whether passwords fulfill all three rules. 

**Hint:** For simplicity, for both 1a and 1b, you can assume that the string input to your functions will only contain letters (lowercase and uppercase); you do not need to consider numbers or special characters.

***

## Task 1a (1 point): `check_length`

Write the function `check_length(password)` that takes as input a string paramter, `password`. It returns `True` if the password is at least 12 characters long, and it returns `False` otherwise. (That means that only Rule 1 from above is implemented.)

***

## Task 1b (1 point): `is_valid`

Write the function `is_valid(password)` that takes as input a string parameter, `password`. It returns `True` if the password fulfills **all 3 rules** above, and `False` otherwise.

In [107]:
# YOUR SOLUTION TO TASK 1A
def check_length(password):
    if len(str(password)) >= 12:
        return True
    else:
        return False
    

print(check_length("thispasswordislongenough"))

True

In [18]:
# Run this cell to verify that your solution to Task 1a is correct
assert check_length("itu") == False
assert check_length("thispasswordislongenough") == True

In [130]:
# YOUR SOLUTION TO TASK 1B
def is_valid(password):
    
    p_str = str(password)
    if len(p_str) < 12:
        return False
    

    #check no repeated characters
   

    p_list = list(p_str)

    p_set = set(p_list)

    if len(p_set) == 1:
        return False


    #check lower case and upper case characters     
    for i in range(len(p_str)):
        if p_str.islower() and p_str.isupper():
            return True 
        else:
            return False

In [132]:
# Run this cell to verify that your solution to Task 1a is correct
assert is_valid("tooshort") == False
assert is_valid("aaaaaaaaaaaa") == False
assert is_valid("PassWord") == False
assert is_valid("onlylowercaseletters") == False
assert is_valid("ONLYUPPERCASELETTERS") == False

***
***

# Task 2: Dice games

## Task 2a (1 point): `roll_exactly(N)`

**Write the function `roll_exactly(N)`** that simulates a dice game in which a die is rolled repeatedly. All points are summed up. The game ends as soon as you obtain `N` or more points (`N` is the function input, an integer number). If with the last dice roll, you obtain **exactly N** points, you win the game. If with the last dice roll, you obtain **more than N** points, you lose the game.
* After each die roll, print out `Die shows: X; points so far: Y` (replace "X" and "Y" by their values). 
* If you reach *exactly* N points, you win; print out `You win`; and the game ends. The function returns `True` in this case. 
* If you *exceed* N points, you lose; print out `You lose`; and the game ends. The function returns `False` in this case.

For example, running `roll_exactly(20)` could show this output: *(note that the exact numbers shown will be different at each function call, since we are working with random numbers)*

```
Die shows 3; points so far: 3
Die shows 6; points so far: 9
Die shows 5; points so far: 14
Die shows 6; points so far: 20
You win!
```

or this output:

```
Die shows 3; points so far: 3
Die shows 6; points so far: 9
Die shows 5; points so far: 14
Die shows 5; points so far: 19
Die shows 6; points so far: 25
You lose!
```

***

## Task 2b (1 point): `roll_exactly_multiplied(N)`

Your friend has been asked to implement a similar function, `roll_exactly_multiplied(N)`, simulating a dice game where the rules are the same as above, but instead of being summed up, the points of each dice roll are **multiplied** with each other. For example, rolling `1` gives you 1 point to start with; rolling `1, 6` gives you $1*6=6$ points; rolling `1, 6, 3` gives you $1 * 6 * 3 = 18$ points; and so on. Unfortunately, your friend has unwittingly written an eternal while loop! Here is their code:

```python
def roll_exactly_multiplied(N): # beware! this function contains an eternal while loop
    total_points = 0
    first_roll = random.choice(range(1,7))
    print(f"Die shows {first_roll}; points so far: {total_points}")
    while total_points < N:
        die = random.choice(range(1,7))
        total_points *= die
        print(f"Die shows {die}; points so far: {total_points}")
    if total_points == N:
        print("You win!")
        return True
    elif total_points > N:
        print("You lose!")
        return False
```


Correct their code so that the `roll_exactly_multiplied(N)` function works as expected. For example, rolling `roll_exactly_multiplied(100)` could show this output: *(note that the exact numbers shown will be different at each function call, since we are working with random numbers)*


```
Die shows 6; points so far: 6
Die shows 2; points so far: 12
Die shows 2; points so far: 24
Die shows 1; points so far: 24
Die shows 5; points so far: 120
You lose!
```

**Hint:** The code for `roll_exactly_multiplied(N)` can be corrected by adding one single line of code directly after the `first_roll` variable is defined.

In [33]:
# import the random module
import random

In [133]:
# YOUR SOLUTION TO TASK 2A
def roll_exactly(N):
    total_points = 0
    first_roll = random.choice(range(1,7))
    total_points += first_roll
    print(f"Die shows {first_roll}; points so far: {total_points}")
    while total_points < N:
        die = random.choice(range(1,7))
        total_points += die
        print(f"Die shows {die}; points so far: {total_points}")
    if total_points == N:
        print("You win!")
        return True
    elif total_points > N:
        print("You lose!")
        return False

In [134]:
# try out your function by running this cell several times
# to see if it works as expected
play_game = roll_exactly(25)
print(f"\nGame won: {play_game}")

Die shows 3; points so far: 3
Die shows 4; points so far: 7
Die shows 1; points so far: 8
Die shows 6; points so far: 14
Die shows 2; points so far: 16
Die shows 1; points so far: 17
Die shows 4; points so far: 21
Die shows 6; points so far: 27
You lose!

Game won: False

In [135]:
# YOUR SOLUTION TO TASK 2B
def roll_exactly_multiplied(N): # beware! this function contains an eternal while loop
    total_points = 0
    first_roll = random.choice(range(1,7))
    total_points += first_roll
    print(f"Die shows {first_roll}; points so far: {total_points}")
    while total_points < N:
        die = random.choice(range(1,7))
        total_points *= die
        print(f"Die shows {die}; points so far: {total_points}")
    if total_points == N:
        print("You win!")
        return True
    elif total_points > N:
        print("You lose!")
        return False

In [136]:
# try out your function by running this cell several times
# to see if it works as expected
play_game = roll_exactly_multiplied(60)
print(f"\nGame won: {play_game}")

Die shows 5; points so far: 5
Die shows 4; points so far: 20
Die shows 6; points so far: 120
You lose!

Game won: False

***

# Task 3: `countries.csv` with pandas

For this task, we'll be working with the [Kaggle](https://www.kaggle.com/datasets/adilshamim8/world-cities-countries-and-languages-dataset) data set "World Cities, Countries & Languages", specifically with the table `countries.csv`. The `countries.csv` file is provided in the same zipped folder as this notebook.

First, read in the `countries.csv` table with `pandas`. Then, with the help of the data set and the methods/functions of your choice (pandas or other), answer the following questions:

## Task 3a (1 point): Countries in Europe smaller than Denmark

**How many countries in Europe have a smaller surface *AND* a smaller population than Denmark?**

To answer this question, filter the `countries` DataFrame with boolean indexing, considering conditions for values in the columns 
* `Continent`,
* `Population`, and
* `SurfaceArea`.

**Hint:** It might be helpful to first define the Population and SurfaceArea values for Denmark as separate variables.

***

## Task 3b (1 point): Countries in Southeast Asia by life expectancy

**Display all countries in southeast Asia, sorted by (descending) life expectancy.** 

To do so:
* Create a copy (using `.copy()`!) of a subset of `countries` that contains only countries in Southeast Asia (filter by values in the column `Region`). 
* Store this dataframe in the variable `se_asia`. 
* Then, sort the dataframe `se_asia` by **descending** life expectancy (i.e., starting with the highest and ending with the lowest life expectancy, sorting the values in the `LifeExpectancy` column);
* Finally, display the sorted dataframe.

In [60]:
# run this cell to import pandas
import pandas as pd

In [97]:
# read in the data set
df = pd.read_csv('countries.csv')
df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [149]:
# YOUR SOLUTION TO TASK 3A


df[ (df["SurfaceArea"]< 43094.0) & (df["Continent"] == "Europe") & (df["Population"] < 5330000) ]

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
4,ALB,Denmark,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
5,AND,Denmark,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
73,FRO,Denmark,Europe,Nordic Countries,1399.0,NaN,43000,78.4,0.0,NaN,Føroyar,Part of Denmark,Margrethe II,901.0,FO
79,GIB,Denmark,Europe,Southern Europe,6.0,NaN,25000,79.0,258.0,NaN,Gibraltar,Dependent Territory of the UK,Elisabeth II,915.0,GI
123,LIE,Denmark,Europe,Western Europe,160.0,1806.0,32300,78.8,1119.0,1084.0,Liechtenstein,Constitutional Monarchy,Hans-Adam II,2446.0,LI
127,LUX,Denmark,Europe,Western Europe,2586.0,1867.0,435700,77.1,16321.0,15519.0,Luxembourg/Lëtzebuerg,Constitutional Monarchy,Henri,2452.0,LU
131,MCO,Denmark,Europe,Western Europe,1.5,1861.0,34000,78.8,776.0,NaN,Monaco,Constitutional Monarchy,Rainier III,2695.0,MC
132,MDA,Denmark,Europe,Eastern Europe,33851.0,1991.0,4380000,64.5,1579.0,1872.0,Moldova,Republic,Vladimir Voronin,2690.0,MD
137,MKD,Denmark,Europe,Southern Europe,25713.0,1991.0,2024000,73.8,1694.0,1915.0,Makedonija,Republic,Boris Trajkovski,2460.0,MK
139,MLT,Denmark,Europe,Southern Europe,316.0,1964.0,380200,77.9,3512.0,3338.0,Malta,Republic,Guido de Marco,2484.0,MT
193,SMR,Denmark,Europe,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,NaN,3171.0,SM
199,SVN,Denmark,Europe,Southern Europe,20256.0,1991.0,1987800,74.9,19756.0,18202.0,Slovenija,Republic,Milan Kucan,3212.0,SI
225,VAT,Denmark,Europe,Southern Europe,0.4,1929.0,1000,NaN,9.0,NaN,Santa Sede/Città del Vaticano,Independent Church State,Johannes Paavali II,3538.0,VA

In [154]:
# YOUR SOLUTION TO TASK 3B

df(df["Region"] == "Southeast Asia") 

df.sort_values(by="LifeExpectancy", ascending=True)

TypeError: 'DataFrame' object is not callable